# Generated by Django 5.1.6 on 2025-03-28 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Amazon', '0003_cartitem_delete_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
