# Generated by Django 5.1.6 on 2025-05-07 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amazon', '0015_alter_contactquery_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, default='', max_length=2500, null=True),
        ),
    ]
