# Generated by Django 5.1.6 on 2025-03-28 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Amazon', '0006_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
