# Generated by Django 5.1.6 on 2025-03-29 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Amazon', '0008_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
