# Generated by Django 5.1.6 on 2025-03-31 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Amazon', '0014_alter_contactquery_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactquery',
            options={'verbose_name_plural': 'contact Queries'},
        ),
    ]
